### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ghost** [csound/csound.github.io#51] opened 2016-09-12 14:14 UTC
Currently, the “Download” page has no description of what are differences between different installation options, how to install, etc.

**Comment by gogins** [comment] 2018-01-15 20:35
I think some minimal qualifying wording would be sufficient: "Prebuilt application," "Prebuilt libraries for developers," "Source code."

More wording would not fit in the current layout, but on the pages linked to there could be more, e.g. "Prebuilt Csound applications and utilities for users," "Prebuilt libraries with header files for people developing software based on Csound," "Source code for developers working on Csound as well as people developing software based on Csound."

**Comment by joachimheintz** [comment] 2023-12-29 14:58
i agree with mike that the download page cannot provide these information by design.
i tried to collect some descriptions in the [floss manual](https://flossmanual.csound.com/how-to/installation), so i am closing this issue.

**Closed by joachimheintz** 2023-12-29 14:58 UTC
Labels: enhancement
